version: '3'
services:
  node:
    build:
      context: .
    ports:
      - "8082:51005"
    environment:
      - DB_HOSTNAME=mysql
    networks:
      - nodeapp-network
    depends_on:
      - mysql
      - mongodb

  mysql:
    container_name: mysql
    image: mysql:5.7
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    volumes:
        - ./data/mysql/:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - nodeapp-network

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - nodeapp-network
    volumes:
        - ./data/mongo/:/var/lib/mongodb
networks:
  nodeapp-network:
    driver: bridge